common: &common
  adapter: postgresql
  host: localhost
  timeout: 5000

development:
  <<: *common
  database: food_forest_dev

test:
  <<: *common
  database: food_forest_test

production:
  <<: *common
  database: food_forest

